"""add total_uses to packages

Revision ID: 03e23e88f505
Revises: 08e841543f28
Create Date: 2026-02-03 00:24:03.624515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e23e88f505'
down_revision = '08e841543f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('supplier')
        batch_op.drop_column('min_quantity')
        batch_op.drop_column('price_per_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_unit', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('min_quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
