"""Fix service booking relationship

Revision ID: 0f0e7d56ebb4
Revises: 9eaf167fd4f6
Create Date: 2026-01-24 08:53:55.417663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0e7d56ebb4'
down_revision = '9eaf167fd4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
