"""upate package model

Revision ID: 1b4b20d43cbe
Revises: cb291bc2b8c8
Create Date: 2026-02-02 12:30:42.510746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4b20d43cbe'
down_revision = 'cb291bc2b8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_uses', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('validity_days', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('badge', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('badge')
        batch_op.drop_column('validity_days')
        batch_op.drop_column('total_uses')

    # ### end Alembic commands ###
