"""Add reference_id to notification model

Revision ID: 3239cd3541f3
Revises: 8b66044f1d9c
Create Date: 2026-02-02 19:36:17.392728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3239cd3541f3'
down_revision = '8b66044f1d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('reference_id')

    # ### end Alembic commands ###
