"""Update package purchases

Revision ID: 8b66044f1d9c
Revises: ebef9bd5d5a7
Create Date: 2026-02-02 18:47:59.119668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b66044f1d9c'
down_revision = 'ebef9bd5d5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_purchases', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
