"""Upgrade Gallery Model

Revision ID: 9eaf167fd4f6
Revises: fbe644993aba
Create Date: 2026-01-02 15:42:06.103692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eaf167fd4f6'
down_revision = 'fbe644993aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
